name: SpellMasons Mods CI

on:
  pull_request:
    branches:    
      - main

jobs:
  SpellMasonsModsCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
        
      # Install Dependencies
      - run: npm ci

      # Build NodeJS App
      - run: npm run build